<?php
if (!defined('ABSPATH')) exit;

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_disinfection_page',
        'title' => 'Страница Дезинфекция',
        'fields' => array(
            // Hero
            array(
                'key' => 'tab_hero',
                'label' => 'Hero',
                'name' => 'tab_hero',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_hero_title',
                'label' => 'Заголовок Hero',
                'name' => 'hero_title',
                'type' => 'text',
                'default_value' => 'Комплексные решения для дезинфекции и инфекционного контроля',
            ),
            array(
                'key' => 'field_hero_desc',
                'label' => 'Описание Hero',
                'name' => 'hero_desc',
                'type' => 'textarea',
                'default_value' => 'Подбираем дезинфицирующие средства, оборудование и расходные материалы для медицинских учреждений, стоматологий, лабораторий и организаций различных сфер деятельности',
            ),
            array(
                'key' => 'field_hero_button_text',
                'label' => 'Текст кнопки Hero',
                'name' => 'hero_button_text',
                'type' => 'text',
                'default_value' => 'Подобрать решение',
            ),
            array(
                'key' => 'field_hero_badges',
                'label' => 'Бейджи Hero',
                'name' => 'hero_badges',
                'type' => 'repeater',
                'min' => 0,
                'max' => 5,
                'layout' => 'table',
                'button_label' => 'Добавить бейдж',
                'sub_fields' => array(
                    array(
                        'key' => 'field_hero_badge_text',
                        'label' => 'Текст',
                        'name' => 'text',
                        'type' => 'text',
                    ),
                ),
            ),
            array(
                'key' => 'field_hero_features',
                'label' => 'Преимущества Hero',
                'name' => 'hero_features',
                'type' => 'repeater',
                'min' => 0,
                'max' => 6,
                'layout' => 'table',
                'button_label' => 'Добавить преимущество',
                'sub_fields' => array(
                    array(
                        'key' => 'field_hero_feature_icon',
                        'label' => 'Иконка',
                        'name' => 'icon',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                    ),
                    array(
                        'key' => 'field_hero_feature_text',
                        'label' => 'Текст',
                        'name' => 'text',
                        'type' => 'text',
                    ),
                ),
            ),

            // Audience
            array(
                'key' => 'tab_audience',
                'label' => 'Кому подходит',
                'name' => 'tab_audience',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_audience_subtitle',
                'label' => 'Подзаголовок',
                'name' => 'audience_subtitle',
                'type' => 'text',
                'default_value' => 'Кому подходит',
            ),
            array(
                'key' => 'field_audience_title',
                'label' => 'Заголовок',
                'name' => 'audience_title',
                'type' => 'text',
                'default_value' => 'Работаем с учреждениями разных направлений',
            ),
            array(
                'key' => 'field_audience_cards',
                'label' => 'Карточки аудиторий',
                'name' => 'audience_cards',
                'type' => 'repeater',
                'min' => 0,
                'max' => 12,
                'layout' => 'block',
                'button_label' => 'Добавить карточку',
                'sub_fields' => array(
                    array(
                        'key' => 'field_audience_card_title',
                        'label' => 'Название',
                        'name' => 'title',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_audience_card_image',
                        'label' => 'Фоновое изображение',
                        'name' => 'image',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                    ),
                    array(
                        'key' => 'field_audience_card_style',
                        'label' => 'Стиль',
                        'name' => 'style',
                        'type' => 'select',
                        'choices' => array(
                            'default' => 'По умолчанию',
                            'gray' => 'Серая',
                            'green' => 'Зелёная',
                            'image' => 'С изображением',
                            'image-overlay' => 'С изображением + затемнение',
                        ),
                        'default_value' => 'default',
                    ),
                ),
            ),

            // Supplies
            array(
                'key' => 'tab_supplies',
                'label' => 'Что мы поставляем',
                'name' => 'tab_supplies',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_supplies_subtitle',
                'label' => 'Подзаголовок',
                'name' => 'supplies_subtitle',
                'type' => 'text',
                'default_value' => 'Что мы поставляем',
            ),
            array(
                'key' => 'field_supplies_title',
                'label' => 'Заголовок',
                'name' => 'supplies_title',
                'type' => 'text',
                'default_value' => 'Все для организации инфекционного контроля',
            ),
            array(
                'key' => 'field_supplies_items',
                'label' => 'Позиции поставок',
                'name' => 'supplies_items',
                'type' => 'repeater',
                'min' => 0,
                'max' => 15,
                'layout' => 'table',
                'button_label' => 'Добавить позицию',
                'sub_fields' => array(
                    array(
                        'key' => 'field_supplies_item_text',
                        'label' => 'Название',
                        'name' => 'text',
                        'type' => 'text',
                    ),
                ),
            ),

            // Included
            array(
                'key' => 'tab_included',
                'label' => 'Что входит',
                'name' => 'tab_included',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_included_subtitle',
                'label' => 'Подзаголовок',
                'name' => 'included_subtitle',
                'type' => 'text',
                'default_value' => 'Что входит',
            ),
            array(
                'key' => 'field_included_title',
                'label' => 'Заголовок',
                'name' => 'included_title',
                'type' => 'text',
                'default_value' => 'Помогаем выстроить систему инфекционного контроля',
            ),
            array(
                'key' => 'field_included_card_text',
                'label' => 'Текст зеленой карточки',
                'name' => 'included_card_text',
                'type' => 'textarea',
                'default_value' => 'Мы помогаем подобрать решения, которые обеспечивают безопасность, удобство использования и соответствие действующим санитарным требованиям',
            ),
            array(
                'key' => 'field_included_cards',
                'label' => 'Карточки "Что входит"',
                'name' => 'included_cards',
                'type' => 'repeater',
                'min' => 0,
                'max' => 10,
                'layout' => 'block',
                'button_label' => 'Добавить карточку',
                'sub_fields' => array(
                    array(
                        'key' => 'field_included_card_image',
                        'label' => 'Изображение',
                        'name' => 'image',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                    ),
                    array(
                        'key' => 'field_included_card_number',
                        'label' => 'Номер',
                        'name' => 'number',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_included_card_title',
                        'label' => 'Заголовок',
                        'name' => 'title',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_included_card_green',
                        'label' => 'Зелёная карточка',
                        'name' => 'is_green',
                        'type' => 'true_false',
                        'default_value' => 0,
                    ),
                ),
            ),

            // Tasks
            array(
                'key' => 'tab_tasks',
                'label' => 'Задачи клиентов',
                'name' => 'tab_tasks',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_tasks_subtitle',
                'label' => 'Подзаголовок',
                'name' => 'tasks_subtitle',
                'type' => 'text',
                'default_value' => 'Популярные задачи клиентов',
            ),
            array(
                'key' => 'field_tasks_title',
                'label' => 'Заголовок',
                'name' => 'tasks_title',
                'type' => 'text',
                'default_value' => 'С чем к нам обращаются чаще всего',
            ),
            array(
                'key' => 'field_tasks_list',
                'label' => 'Список задач',
                'name' => 'tasks_list',
                'type' => 'repeater',
                'min' => 0,
                'max' => 10,
                'layout' => 'table',
                'button_label' => 'Добавить задачу',
                'sub_fields' => array(
                    array(
                        'key' => 'field_task_icon',
                        'label' => 'Иконка',
                        'name' => 'icon',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                    ),
                    array(
                        'key' => 'field_task_text',
                        'label' => 'Текст',
                        'name' => 'text',
                        'type' => 'text',
                    ),
                ),
            ),

            // Why choose
            array(
                'key' => 'tab_why',
                'label' => 'Почему выбирают',
                'name' => 'tab_why',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_why_subtitle',
                'label' => 'Подзаголовок',
                'name' => 'why_subtitle',
                'type' => 'text',
                'default_value' => 'Почему выбирают ТриМед',
            ),
            array(
                'key' => 'field_why_title',
                'label' => 'Заголовок',
                'name' => 'why_title',
                'type' => 'text',
                'default_value' => 'Надёжный поставщик для медицинских учреждений региона',
            ),
            array(
                'key' => 'field_why_features',
                'label' => 'Преимущества',
                'name' => 'why_features',
                'type' => 'repeater',
                'min' => 0,
                'max' => 6,
                'layout' => 'table',
                'button_label' => 'Добавить преимущество',
                'sub_fields' => array(
                    array(
                        'key' => 'field_why_feature_text',
                        'label' => 'Текст',
                        'name' => 'text',
                        'type' => 'text',
                    ),
                ),
            ),

            // Projects
            array(
                'key' => 'tab_projects',
                'label' => 'Проекты',
                'name' => 'tab_projects',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_projects_title',
                'label' => 'Заголовок',
                'name' => 'projects_title',
                'type' => 'text',
                'default_value' => 'Реализованные проекты',
            ),
            array(
                'key' => 'field_projects_desc',
                'label' => 'Описание',
                'name' => 'projects_desc',
                'type' => 'textarea',
                'default_value' => 'За время работы мы реализовали проекты по оснащению медицинских кабинетов и центров в Забайкальском крае. Мы понимаем специфику региона, требования врачей и реальные условия работы.',
            ),

            // Partners
            array(
                'key' => 'tab_partners',
                'label' => 'Партнёры',
                'name' => 'tab_partners',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_partners_title',
                'label' => 'Заголовок',
                'name' => 'partners_title',
                'type' => 'text',
                'default_value' => 'Работаем с ведущими производителями',
            ),
            array(
                'key' => 'field_partners',
                'label' => 'Партнёры',
                'name' => 'partners',
                'type' => 'repeater',
                'min' => 0,
                'max' => 6,
                'layout' => 'block',
                'button_label' => 'Добавить партнёра',
                'sub_fields' => array(
                    array(
                        'key' => 'field_partner_logo',
                        'label' => 'Логотип',
                        'name' => 'logo',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                    ),
                    array(
                        'key' => 'field_partner_name',
                        'label' => 'Название',
                        'name' => 'name',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_partner_desc',
                        'label' => 'Описание',
                        'name' => 'desc',
                        'type' => 'textarea',
                    ),
                ),
            ),

            // FAQ
            array(
                'key' => 'tab_faq',
                'label' => 'FAQ',
                'name' => 'tab_faq',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_faq_title',
                'label' => 'Заголовок',
                'name' => 'faq_title',
                'type' => 'text',
                'default_value' => 'Часто задаваемые вопросы',
            ),
            array(
                'key' => 'field_faq_items',
                'label' => 'Вопросы и ответы',
                'name' => 'faq_items',
                'type' => 'repeater',
                'min' => 0,
                'max' => 12,
                'layout' => 'block',
                'button_label' => 'Добавить вопрос',
                'sub_fields' => array(
                    array(
                        'key' => 'field_faq_question',
                        'label' => 'Вопрос',
                        'name' => 'question',
                        'type' => 'text',
                    ),
                    array(
                        'key' => 'field_faq_answer',
                        'label' => 'Ответ',
                        'name' => 'answer',
                        'type' => 'textarea',
                    ),
                    array(
                        'key' => 'field_faq_open',
                        'label' => 'Открыт по умолчанию',
                        'name' => 'is_open',
                        'type' => 'true_false',
                        'default_value' => 0,
                    ),
                ),
            ),

            // Application
            array(
                'key' => 'tab_application',
                'label' => 'Форма заявки',
                'name' => 'tab_application',
                'type' => 'tab',
                'placement' => 'left',
            ),
            array(
                'key' => 'field_application_title',
                'label' => 'Заголовок формы',
                'name' => 'application_title',
                'type' => 'text',
                'default_value' => 'Подберём решение для вашего учреждения',
            ),
            array(
                'key' => 'field_application_desc',
                'label' => 'Описание формы',
                'name' => 'application_desc',
                'type' => 'textarea',
                'default_value' => 'Оставьте заявку, и специалист поможет подобрать оборудование, дезинфицирующие средства и расходные материалы под ваши задачи.',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-disinfection.php',
                ),
            ),
        ),
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
    ));
}
